name: Deploy to Lightsail


on:

  push:

    branches:

      - main


jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy via SSH

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SERVER_IP }}

          username: ubuntu

          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd /var/www/kafu

            git pull origin main

            php artisan config:cache


